@HelpDesk_HostAddress = http://localhost:8000

GET {{HelpDesk_HostAddress}}/api/tickets
Accept: application/json

### 

GET {{HelpDesk_HostAddress}}/api/tickets/1
Accept: application/json

### 

POST {{HelpDesk_HostAddress}}/api/tickets
Content-Type: application/json

{
    "title": "Problem med login",
    "description": "Kan inte logga in med mitt konto"
}

###

POST {{HelpDesk_HostAddress}}/api/tickets/1/assign
Content-Type: application/json

{
  "assignedTo": "Nils Nilsson"
}
